name: USPACE Monitor

schedule:
  - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: uspace-monitor
  cancel-in-progress: false

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python monitor.py

      - name: Save last_count
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add last_count.txt

          if git diff --cached --quiet; then
            echo "last_count.txt 沒有變化，不需要 commit"
            exit 0
          fi

          git commit -m "Update last_count"
          git pull --rebase origin main
          git push origin main
